# Generated by Django 5.2 on 2025-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_companyinfo_email_companyinfo_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_us',
            field=models.TextField(default='', verbose_name='О нас'),
            preserve_default=False,
        ),
    ]
