# Generated by Django 5.2 on 2025-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_companyinfo_why_it_is_cheaper_to_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Метрика')),
                ('label', models.CharField(max_length=255, verbose_name='Подпись')),
                ('small_label', models.CharField(max_length=255, verbose_name='Подпись снизу')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
