# Generated by Django 5.2 on 2025-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companystat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystat',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Метрика'),
        ),
    ]
