# Generated by Django 5.2 on 2025-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_privacypolicy_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='personal_data_policy/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Обработка персональных данных',
                'verbose_name_plural': 'Обработка персональных данных',
            },
        ),
    ]
