# Generated by Django 5.2 on 2025-05-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_personaldatapolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='telegram',
            field=models.CharField(default='', max_length=255, verbose_name='Telegram'),
            preserve_default=False,
        ),
    ]
